# Generated by Django 6.0.4 on 2026-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('genero', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('reggaeton', 'Reggaetón'), ('hip_hop', 'Hip Hop'), ('electronica', 'Electrónica'), ('jazz', 'Jazz'), ('clasica', 'Clásica'), ('salsa', 'Salsa'), ('cumbia', 'Cumbia'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('duracion_segundos', models.PositiveIntegerField(help_text='Duración en segundos')),
                ('fecha_lanzamiento', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'canciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
